function c = colors( this )

c = {'wdAuto',...
    'wdBlack',...
    'wdBlue',...
    'wdBrightGreen',...
    'wdByAuthor',...
    'wdDarkBlue',...
    'wdDarkRed',...
    'wdDarkYellow',...
    'wdGray25',...
    'wdGray50',...
    'wdGreen',...
    'wdNoHighlight',...
    'wdPink',...
    'wdRed',...
    'wdTeal',...
    'wdTurquoise',...
    'wdViolet',...
    'wdWhite',...
    'wdYellow'};